# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

# update Makefile if target boards added
env:
    global:
        - CXX=g++-5
    #- PLATFORMIO_BOARD=uno
    - PLATFORMIO_BOARD=nodemcuv2

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - lcov
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cppcheck

install:
    - pip install -U platformio
    #- platformio lib install 44

script:
    - platformio run
    # Build and run unit tests
    #- bash test/run_tests.sh
    # Run static code analysis over the source code
    - cppcheck --std=c++11 --enable=performance,portability,information --quiet --error-exitcode=1 src/
    #- platformio ci --lib="." --board=nodemcuv2

after_success:
    - bash run_coverage.sh
    # Upload report to codecov
    #- bash <(curl -s https://codecov.io/bash) -s coverage-reports || echo "Codecov did not collect coverage reports"
    # Generate documentation
    - doxygen Doxyfile     

 notifications:
    email: false

    slack:
        rooms:
            secure: <enter secure hash-key for slack-channel here>
        on_failure: always
        on_success: change
